In [7]:
import numpy as np
labels=np.array([-2,-1,-1,0,1,2,3,4,5])


In [27]:
s=np.nonzero(labels==6)
print(type(s))
print(np.any(s))

<class 'tuple'>
False


In [28]:
x = np.array([1,2,3])
y = np.array([4,5,6,7])

xv,yv = np.meshgrid(x,y,indexing = 'xy')

xv2,yv2 = np.meshgrid(x,y,indexing = 'ij')

In [33]:
print(xv)
print(yv)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]


In [34]:
print(xv2)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [35]:
print(yv2)

[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]


In [38]:
s=[0,1,2]
s.any()

AttributeError: 'list' object has no attribute 'any'

In [41]:
if 1!=0:
    print('chiyu')

chiyu


In [54]:
np.any([0,-1])

True

In [55]:
np.all([0,-1])

False

In [46]:
np.any([1,1])

True

In [47]:
np.any([0,0])

False

In [52]:
np.any([-1,1])

True

In [53]:
np.all([-1,-1])

True